### PR TITLE
Updated install requirements with libsctp

### PR DESCRIPTION
**Pull request by jfagoagas**

### CODE REVIEW

**Comment by omprakashpuniya5132** [comment]
ok good

**Comment by omprakashpuniya5132** [comment]
root@kali:~/SigPloit# python3 sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
ModuleNotFoundError: No module named 'attacks'
can help me

**Review by omprakashpuniya5132 — APPROVED** [review]
root@kali:~/SigPloit# python3 sigploit.py
Traceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/root/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/root/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/root/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/root/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
ModuleNotFoundError: No module named 'attacks'

**Comment by odinaka1** [comment]
Contact me @ nmarcil073@gmail.com

**Comment by JamesSmi-ux** [comment]
@odinaka1 , you know about ss7 sms intercept? Can I contact you on mail ? Thanks

**Comment by kaliss7s** [comment]
eny one pls help me to fix this pls pls pls 


raceback (most recent call last):
  File "sigploit.py", line 16, in <module>
    from ss7.tracking import *
  File "/home/linux/SigPloit/ss7/tracking.py", line 14, in <module>
    import sigploit
  File "/home/linux/SigPloit/sigploit.py", line 21, in <module>
    from gtpmain import *
  File "/home/linux/SigPloit/gtpmain.py", line 12, in <module>
    import gtp.info
  File "/home/linux/SigPloit/gtp/info.py", line 18, in <module>
    from attacks.info import discover_gtp_nodes
  File "/home/linux/SigPloit/gtp/attacks/info/discover_gtp_nodes.py", line 39, in <module>
    from gtp_v2_core.utilities.configuration_parser import parseConfigs
  File "/home/linux/SigPloit/gtp/gtp_v2_core/utilities/configuration_parser.py", line 38, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj

**Review by TheTangledMind — APPROVED** [review]

**Comment by partalian** [comment]
Hi all, just paid yesterday at 13:56 to ss7.dev $1000 (got all the proof), nothing happened.
No answer, sent 3-4 emails to them and nobody came back.
In case you stumble upon this website, beware IT IS A SCAM.
If you need ss7 then look elsewhere (don't know yet either).
ss7.dev - SCAM PAGE and money lost!

**Comment by TheTangledMind** [comment]
thanks for that. i am sry for your loss there

**Review by Boob6667 — APPROVED** [review]

**Pull request closed without merging**
